---
apiVersion: v1
data:
  django.conf: |-
      server {
           listen 80 default_server;
           server_name _;
           root /home/ubuntu/new_chatapp-master/fundoo;
           location / {
             include proxy_params;
             proxy_pass http://backendserv:8000;
             }
            location /static/ {
              autoindex on;
              alias /home/ubuntu/new_chatapp-master/fundoo/fundooapp/static/;
             }
      }
kind: ConfigMap
metadata:
  name: nginx-config
