stages:
    - build
    - test
install dependencies:
    stage: build
    image: ubuntu:18.04
    script:
        - apt-get update
        - apt-get -y install python3-pip python-dev nginx git
        - pip3 install virtualenv
        - virtualenv env
        - source env/bin/activate
        - git clone https://github.com/suraj9741/new_chatapp-master.git
        - ls
        - cd new_chatapp-master
        - pip3 install -r requirements.txt
        - pip3 install django bcrypt django-extensions
        - pip3 install gunicorn
        - ls /etc/systemd/system/
        - cd fundoo
        - python3 manage.py migrate
    artifacts:
        paths:
            - env
            - new_chatapp-master
test:
    stage: test
    image: ubuntu:18.04
    script:
        - source env/bin/activate
        - cd new_chatapp-master/fundoo
        - ls
        - python3 manage.py migrate
